inventory.list.error.message = Erro ao listar movimentos.
inventory.get.error.message = Erro ao obter movimento.

inventory.save.success.message = Movimento registrado com sucesso.
inventory.save.error.message = Erro ao salvar movimento.

inventory.update.success.message = Movimento atualizado com sucesso.
inventory.update.error.message = Erro ao atualizar movimento.

inventory.save.already.message = Este movimento já está cadastrado.
