receivable.list.error.message = Erro ao listar pagamentos.

receivable.not.found.message = Pagamento não encontrado.

receivable.save.success.message = Pagamento registrado com sucesso.
receivable.save.error.message = Erro ao salvar pagamento.

receivable.get.error.message = Erro ao obter o pagamento.

receivable.update.success.message = Pagamento atualizado com sucesso.
receivable.update.error.message = Erro ao atualizar pagamento.